name: dart_app_architecture_cli
description: Deriv App Architecture CLI

version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_style: ^2.2.4
  dcli: ^1.34.0
  path: ^1.8.0
  recase: ^4.1.0
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
